-- Optional manual migration (startup also runs ADD COLUMN IF NOT EXISTS in database.go).
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gst_number TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_fee DOUBLE PRECISION NOT NULL DEFAULT 0;
